# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CatchUp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘FeedlyKit’
  pod 'NXOAuth2Client', '~> 1.2.8'
  pod 'Optimizely-iOS-SDK'

  # Pods for CatchUp

end
